/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ApiTokenRouteImport } from './routes/api/token'
import { Route as ApiLookupRouteImport } from './routes/api/lookup'
import { Route as ApiPublicStatusRouteImport } from './routes/api/public/status'
import { Route as ApiPublicHealthRouteImport } from './routes/api/public/health'

const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiTokenRoute = ApiTokenRouteImport.update({
  id: '/api/token',
  path: '/api/token',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiLookupRoute = ApiLookupRouteImport.update({
  id: '/api/lookup',
  path: '/api/lookup',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicStatusRoute = ApiPublicStatusRouteImport.update({
  id: '/api/public/status',
  path: '/api/public/status',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicHealthRoute = ApiPublicHealthRouteImport.update({
  id: '/api/public/health',
  path: '/api/public/health',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/auth': typeof AuthRoute
  '/api/lookup': typeof ApiLookupRoute
  '/api/token': typeof ApiTokenRoute
  '/api/public/health': typeof ApiPublicHealthRoute
  '/api/public/status': typeof ApiPublicStatusRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/auth': typeof AuthRoute
  '/api/lookup': typeof ApiLookupRoute
  '/api/token': typeof ApiTokenRoute
  '/api/public/health': typeof ApiPublicHealthRoute
  '/api/public/status': typeof ApiPublicStatusRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/auth': typeof AuthRoute
  '/api/lookup': typeof ApiLookupRoute
  '/api/token': typeof ApiTokenRoute
  '/api/public/health': typeof ApiPublicHealthRoute
  '/api/public/status': typeof ApiPublicStatusRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/auth'
    | '/api/lookup'
    | '/api/token'
    | '/api/public/health'
    | '/api/public/status'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin'
    | '/auth'
    | '/api/lookup'
    | '/api/token'
    | '/api/public/health'
    | '/api/public/status'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/auth'
    | '/api/lookup'
    | '/api/token'
    | '/api/public/health'
    | '/api/public/status'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRoute
  AuthRoute: typeof AuthRoute
  ApiLookupRoute: typeof ApiLookupRoute
  ApiTokenRoute: typeof ApiTokenRoute
  ApiPublicHealthRoute: typeof ApiPublicHealthRoute
  ApiPublicStatusRoute: typeof ApiPublicStatusRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/token': {
      id: '/api/token'
      path: '/api/token'
      fullPath: '/api/token'
      preLoaderRoute: typeof ApiTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/lookup': {
      id: '/api/lookup'
      path: '/api/lookup'
      fullPath: '/api/lookup'
      preLoaderRoute: typeof ApiLookupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/status': {
      id: '/api/public/status'
      path: '/api/public/status'
      fullPath: '/api/public/status'
      preLoaderRoute: typeof ApiPublicStatusRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/health': {
      id: '/api/public/health'
      path: '/api/public/health'
      fullPath: '/api/public/health'
      preLoaderRoute: typeof ApiPublicHealthRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRoute,
  AuthRoute: AuthRoute,
  ApiLookupRoute: ApiLookupRoute,
  ApiTokenRoute: ApiTokenRoute,
  ApiPublicHealthRoute: ApiPublicHealthRoute,
  ApiPublicStatusRoute: ApiPublicStatusRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
